#coding: utf-8
Texts = dict(
	index_title = "MinoCMS",
	index_slogan = "Welcome to MinoCMS",
	index_description = "Sign In",
	index_label_username = "Nickname",
	index_input_username = "Username",
	index_label_password = "Password",
	index_input_password = "Password",
	index_submit_button = "Enter",
	register_title = "MiniCMS",
	register_slogan = "UA fast system and easy to use",
	register_description = "Sign Up, is free and is required for explore the world",
	register_label_username = "User",
	register_username_name = "Nickname",
	register_label_password = "Password",
	register_password_name = "Password",
	register_label_mail = "E-Mail",
	register_mail_name = "E-Mail",
	register_button_submit = "Finish"
	)
index_title = Texts['index_title']
index_slogan = Texts['index_slogan']
index_description = Texts['index_description']
index_label_username = Texts['index_label_username']
index_input_username = Texts['index_input_username']
index_label_password = Texts['index_label_password']
index_input_password = Texts['index_input_password']
index_submit_button = Texts['index_submit_button']
register_title = Texts['register_title']
register_slogan = Texts['register_slogan']
register_description = Texts['register_description']
register_label_username = Texts['register_label_username']
register_input_username = Texts['register_username_name']
register_label_password = Texts['register_label_password']
register_input_password = Texts['register_password_name']
register_label_mail = Texts['register_label_mail']
register_input_mail = Texts['register_mail_name']
register_button_submit = Texts['register_button_submit']